/**
 * dsh-widgets showcase — widget data. GENERATED by website/gen-site.mjs.
 *
 * SOURCE OF TRUTH: this file mirrors the real project unit directories
 * `src/widgets/<id>/manifest.json` (55 units, v1.8.0). Every field
 * below comes from those manifests — nothing is invented. Regenerate with
 * `node website/gen-site.mjs`; verify with `--check` (wired into verify.mjs).
 */
window.DASH_WIDGETS = {
  version: '1.8.0',
  npm: 'dsh-widgets',
  repo: 'https://github.com/Physicolor/dsh-widgets',
  issues: 'https://github.com/Physicolor/dsh-widgets/issues',
  releases: 'https://github.com/Physicolor/dsh-widgets/releases',
  site: 'https://physicolor.github.io/dsh-widgets/',
  installCmd: 'dsh plugin --profile web add dsh-widgets',
  compat: 'DeepSeek Harness 0.1.0-rc.6+',
  groups: {
    'system': { en: 'System', zh: '系统' },
    'commandcode': { en: 'Command Code', zh: 'Command Code' },
    'coding-plan': { en: 'Coding Plan Usage', zh: 'Coding Plan 用量' },
    'opencode-go': { en: 'OpenCode Go', zh: 'OpenCode Go' },
    'pricing': { en: 'Peak Pricing', zh: '峰谷定价' },
    'device': { en: 'Device', zh: '设备状态' },
    'github': { en: 'GitHub', zh: 'GitHub' },
    'other': { en: 'Others', zh: '其它' }
  },
  widgets: [
    {
      id: 'counts', name: 'Turns · Steps', nameZh: '轮次·步数',
      desc: 'Turns and steps of the current session',
      descZh: '本轮会话的轮次与步骤计数',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 10
    },
    {
      id: 'llm', name: 'LLM Time', nameZh: 'LLM 时长',
      desc: 'Cumulative model inference time',
      descZh: '模型推理累计耗时',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 11
    },
    {
      id: 'tool', name: 'Tool Calls', nameZh: '工具调用',
      desc: 'Three detail rows (default 失败 / 平均每次 / 工具耗时占比) under the cumulative-time figure; rows are swappable in Config',
      descZh: '明细三行（默认 失败 / 平均每次 / 工具耗时占比），大字为累计耗时；行可在组件配置里更换',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 12
    },
    {
      id: 'ttft', name: 'Avg TTFT', nameZh: '首 token 平均',
      desc: 'Average first-token latency',
      descZh: '平均首 token 延迟',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 13
    },
    {
      id: 'tps', name: 'Rate', nameZh: '速率',
      desc: 'Decode throughput speed',
      descZh: '解码吞吐速度',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 14
    },
    {
      id: 'cache', name: 'Cache Hit', nameZh: '缓存命中',
      desc: 'Cache hit rate as a ring, with this session\'s token breakdown',
      descZh: '缓存命中率环图与本次会话的 token 构成',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 15
    },
    {
      id: 'tokens', name: 'Session Tokens', nameZh: '会话 Token',
      desc: 'This session\'s token total with its input / output split (session scope, not the per-day cross-session usage)',
      descZh: '本次会话的 token 总量与输入 / 输出构成（会话内口径，不是逐日跨会话的用量）',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 16
    },
    {
      id: 'context', name: 'Context Compaction', nameZh: '上下文压缩',
      desc: 'Context usage percent with the top-right two-tap Compact button; below it folds / reclaimed tokens / items folded',
      descZh: '上下文占用百分比 + 右上角按钮两次点击执行压缩；下方是压缩次数 / 累计回收 / 折叠项数',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 20
    },
    {
      id: 'context-water', name: 'Context Level', nameZh: '上下文水位',
      desc: 'System/tools/messages share as a segmented bar',
      descZh: '上下文系统/工具/消息占比分段条',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2', '2x4'], order: 21
    },
    {
      id: 'task', name: 'Tasks', nameZh: '任务',
      desc: 'The todo entries themselves: the figure is the in-progress count with the counts line beside it, then up to four rows (in-progress first, then pending); an empty list shows "No tasks"',
      descZh: '任务条目明细：大字为进行中数量（右侧灰字是进行中 / 待办计数），下方按进行中优先列出条目本身，最多 4 行；没有任务时显示「暂无任务」',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2', '2x4'], order: 22
    },
    {
      id: 'trajectory', name: 'Trajectory', nameZh: '对话轨迹',
      desc: 'The official Trajectory rail as a card: one colored bar per input / model / tool beat, rolling right as the model keeps calling tools',
      descZh: '官方「轨迹」三色泳道的卡片版：输入 / 模型 / 工具 每次触发一根色条，随模型调用工具实时右移滚动',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 23
    },
    {
      id: 'harness-board', name: 'Session Overview', nameZh: '会话概览',
      desc: 'The session numbers the composer stats line was split into, on ONE 2×4: turns / LLM / tools / rate by default, up to ten, picked and row-dragged in the component config (five per row, wrapping to two rows; a 2×2 card prints its figure at 20px, a board figure is 13px — the board scans a row, the card shows one number)',
      descZh: '把输入框底部那条统计拆出来的会话数字并成一张 2×4：默认 轮次 / LLM / 工具 / 速率，最多 10 个，在组件配置里勾选 + 拖动整行排序（每行最多 5 个、超过自动折成两行；单张 2×2 卡的数字是 20px，这里是 13px——看板用来扫一排，单卡用来看一个）',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x4'], order: 24
    },
    {
      id: 'quote', name: 'Daily Quote', nameZh: '今日寄语',
      desc: 'Shows a custom sentence you typed (hidden while empty)',
      descZh: '显示你自定义的一句话（未填写文本时不显示内容）',
      group: 'other', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 30
    },
    {
      id: 'heatmap', name: 'Token Heatmap', nameZh: '用量热度图',
      desc: 'Daily token usage heatmap (self-accounted). 2×2 shows a ~3-month calendar, 2×4 the ~half-year history; switch size in the market',
      descZh: '每日 Token 用量热度图（自记账）。2×2 显示近 3 个月日历，2×4 显示近半年全部用量点；大小可在市场左右切换',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2', '2x4'], order: 40
    },
    {
      id: 'heatmap-bars', name: 'Token Bars', nameZh: '用量柱状图',
      desc: 'Daily token-usage bars with a 7-day / 30-day window setting; the 2×4 moves the figures into the title row with MAX/TOTAL labels',
      descZh: '逐日 Token 用量柱状图，窗口可在 7 天 / 30 天之间配置；2×4 宽版把合计与峰值移到标题行右端并带 MAX/TOTAL 标头',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2', '2x4'], order: 41
    },
    {
      id: 'quota-manage', name: 'Quota Manager', nameZh: '额度管理',
      desc: 'Projects the month-end usage percent from the billing period\'s pace, with today\'s tokens vs the recommended budget',
      descZh: '按账期趋势预测月末用量百分比，并给出今日 token 用量与今日推荐用量',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 42
    },
    {
      id: 'usage-bars', name: 'Usage Bars', nameZh: '用量对比',
      desc: 'OpenCode rolling/weekly/monthly usage bars',
      descZh: 'OpenCode 滚动/周/月三窗口用量柱状图',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 50
    },
    {
      id: 'usage-rings', name: 'Usage Rings', nameZh: '用量环图',
      desc: 'OpenCode rolling/weekly/monthly usage rings',
      descZh: 'OpenCode 滚动/周/月三窗口用量环形图',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 51
    },
    {
      id: 'usage-rolling', name: 'Rolling Usage', nameZh: '滚动用量',
      desc: 'OpenCode Go rolling-window usage quota',
      descZh: 'OpenCode Go 滚动窗口用量配额',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 52
    },
    {
      id: 'usage-weekly', name: 'Weekly Usage', nameZh: '每周用量',
      desc: 'OpenCode Go weekly usage quota',
      descZh: 'OpenCode Go 每周用量配额',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 53
    },
    {
      id: 'usage-monthly', name: 'Monthly Usage', nameZh: '每月用量',
      desc: 'OpenCode Go monthly usage quota',
      descZh: 'OpenCode Go 每月用量配额',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 54
    },
    {
      id: 'cc-whoami', name: 'Account', nameZh: '账户',
      desc: 'Current Command Code account identity (name / email / org)',
      descZh: '当前 Command Code 账户身份（用户名 / 邮箱 / 组织）',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 60
    },
    {
      id: 'peak-pricing', name: 'Peak Pricing', nameZh: '峰谷定价',
      desc: 'DeepSeek V4 peak pricing: whether now is a peak window (Beijing time, weekdays 09:00–12:00 & 14:00–18:00; weekends and Chinese public holidays are off-peak all day)',
      descZh: 'DeepSeek V4 峰谷定价：当前是否处于高峰时段（北京时间工作日 09:00–12:00 与 14:00–18:00 为高峰；周末与中国法定节假日全天低谷）',
      group: 'pricing', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 60
    },
    {
      id: 'sys-cpu', name: 'CPU Status', nameZh: 'CPU 状态',
      desc: 'Local CPU utilization and memory usage',
      descZh: '本机 CPU 利用率与内存占用',
      group: 'system', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 60
    },
    {
      id: 'cc-usage', name: 'Usage', nameZh: '用量',
      desc: 'Requests, success rate, tokens and spend for the billing period',
      descZh: '账期内的请求数、成功率、Token 与消费摘要',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 61
    },
    {
      id: 'sys-gpu', name: 'GPU Status', nameZh: 'GPU 状态',
      desc: 'Local NVIDIA GPU VRAM, utilization and temperature',
      descZh: '本机 NVIDIA GPU 显存、利用率与温度',
      group: 'system', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 61
    },
    {
      id: 'cc-credits', name: 'Credits', nameZh: '额度',
      desc: 'Credit balance with 5h / weekly window usage',
      descZh: 'Credits 余额与 5h / 周额度窗口用量',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 62
    },
    {
      id: 'sys-rings', name: 'CPU · GPU Rings', nameZh: 'CPU·GPU 环图',
      desc: 'CPU / GPU utilization twin rings',
      descZh: 'CPU / GPU 利用率双环形图',
      group: 'system', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 62
    },
    {
      id: 'cc-windows', name: 'Windows', nameZh: '窗口',
      desc: '5h / weekly / monthly usage as rings',
      descZh: '5h / 周 / 月 三窗口用量环图',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 63
    },
    {
      id: 'sys-board', name: 'System Monitor', nameZh: '系统监控',
      desc: 'CPU / memory / GPU VRAM and utilization dashboard rings',
      descZh: 'CPU/内存/GPU 显存与利用率全指标环形看板',
      group: 'system', builtin: false, defaultInstalled: false, sizes: ['2x4'], order: 63
    },
    {
      id: 'cc-subscription', name: 'Plan', nameZh: '套餐',
      desc: 'Current plan tier (GOAT / Pro / Max …) and the billing period end',
      descZh: '当前套餐等级（GOAT / Pro / Max …）与账期结束时间',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 64
    },
    {
      id: 'sys-gpu-line', name: 'GPU Utilization', nameZh: 'GPU 利用率',
      desc: 'GPU utilization sparkline (last ~20 min)',
      descZh: 'GPU 利用率折线（最近约 20 分钟）',
      group: 'device', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 64
    },
    {
      id: 'cc-window-5h', name: '5h window', nameZh: '5h 窗口',
      desc: '5-hour quota window usage percent and reset time',
      descZh: '5 小时额度窗口用量百分比与重置时间',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 65
    },
    {
      id: 'cc-window-weekly', name: 'Weekly window', nameZh: '周窗口',
      desc: 'Weekly quota window usage percent and reset time',
      descZh: '周额度窗口用量百分比与重置时间',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 66
    },
    {
      id: 'cc-window-monthly', name: 'Monthly window', nameZh: '月窗口',
      desc: 'Billing-period usage percent ((allowance − remaining) / allowance) and period end',
      descZh: '账期月额度用量百分比（额度 − 剩余 / 额度）与账期结束时间',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 67
    },
    {
      id: 'github-contrib', name: 'Contribution Heatmap', nameZh: '提交热度图',
      desc: 'GitHub contribution calendar in GitHub\'s own five-step green. 2×2 covers ~3 months, 2×4 the last year (the window GitHub\'s profile header reports); reads this machine\'s login unless a user is set',
      descZh: 'GitHub 提交热度图（同款 5 级绿）。2×2 近 3 个月，2×4 近一年（与 GitHub 个人页同款窗口）；默认读本机已登录的账号，也可填用户名',
      group: 'github', builtin: false, defaultInstalled: false, sizes: ['2x2', '2x4'], order: 70
    },
    {
      id: 'github-stars', name: 'Stars', nameZh: 'Stars',
      desc: 'Repo stars with the repo name above and forks below; tap the card to cycle when several repos are watched',
      descZh: '仓库 Stars（副标题是仓库名，副行是 Forks）；同时监控多个仓库时单击卡片切换',
      group: 'github', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 71
    },
    {
      id: 'github-issues', name: 'Issues', nameZh: '问题',
      desc: 'Open issues (PRs excluded), with how many nobody has answered underneath — measured only with a token, otherwise the line says so',
      descZh: '未关闭 Issue 数（不含 PR），副行是其中没有任何人回复的数量——配了 token 才测得到，否则显示「回复（配置 token 后可测）」',
      group: 'github', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 72
    },
    {
      id: 'github-push', name: 'Pushes', nameZh: '提交',
      desc: 'How long since the last push (12s / 5m / 3h / 6d), with the newest release tag underneath',
      descZh: '距离最近一次 push 多久（12s / 5m / 3h / 6d），副行是最新 Release tag',
      group: 'github', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 73
    },
    {
      id: 'github-board', name: 'Repo Pulse', nameZh: '仓库脉搏',
      desc: '2×4 board: stars / open issues / unanswered / last push side by side, with the full repo name and newest release on the title row',
      descZh: '2×4 汇总板：Stars / 未关闭 Issue / 未回复 / 最近提交 并排，标题行给出仓库全名与最新 Release',
      group: 'github', builtin: false, defaultInstalled: false, sizes: ['2x4'], order: 74
    },
    {
      id: 'usage-mix', name: 'Plan Overview', nameZh: '套餐总览',
      desc: 'Cross-platform quota board: today\'s tokens first, the board\'s tightest occupancy as a head ring, then one row per platform (its second key pool reads Ⅱ)',
      descZh: '跨平台额度看板：今日用量打头，右上角环形显示全场最紧的占用，下面每个平台（含号池，第二个用罗马数字 Ⅱ）各占一行',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 79
    },
    {
      id: 'trajectory-stats', name: 'Trajectory Share', nameZh: '轨迹占比',
      desc: 'The stats view of Trajectory: each lane\'s time and share of the window; tap to switch the figure between model and tool',
      descZh: '「对话轨迹」的统计版：输入 / 模型 / 工具 各自的时长与占比，点按可切换大数字看模型或工具',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 80
    },
    {
      id: 'model-config', name: 'Session Config', nameZh: '会话配置',
      desc: 'The model route, reasoning effort and agent preset this session runs; flags a route change queued for the next request',
      descZh: '本会话正在用的模型 / 推理档 / Agent 预设；下一轮请求换了路线时会显示出来',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 82
    },
    {
      id: 'peak-pricing-board', name: 'Peak Hours Board', nameZh: '峰谷时段表',
      desc: 'The 2×4 peak-pricing timetable: how the rest of today bills — peak 09:00–12:00 / 14:00–18:00, off-peak otherwise, the row billing right now highlighted, plus how long until the rate flips; weekends and Chinese public holidays say why they are off-peak all day (same rule as the 2×2 Peak Pricing card; windows, zone and extra off-peak days configurable)',
      descZh: '2×4 宽版峰谷定价：今天接下来的计费时刻表——高峰 09:00–12:00 / 14:00–18:00、其余低谷，正在计费的那一行高亮，并给出距离下一段切换还有多久；周末与中国法定节假日写明「全天低谷」的原因（与 2×2 峰谷定价同一套规则；可自定时段 / 时区 / 额外低谷日）',
      group: 'pricing', builtin: false, defaultInstalled: false, sizes: ['2x4'], order: 82
    },
    {
      id: 'goal-progress', name: 'Goal Progress', nameZh: '目标进度',
      desc: 'The active goal\'s round progress and lifecycle phase — the only progress truth an autonomous run has',
      descZh: '当前目标的轮次进度与阶段（自主长跑时唯一可信的进度真相）',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 83
    },
    {
      id: 'subagent', name: 'Subagents', nameZh: '子代理',
      desc: 'How many subagents this session spawned, how long each has been active, and their labels',
      descZh: '本会话派生的子代理数量、各自活跃时长与身份标签',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 84
    },
    {
      id: 'guard', name: 'Permissions', nameZh: '权限档位',
      desc: 'The effective permission preset and what it allows — the projection already folds preset, sandbox mode and approval policy into this one value',
      descZh: '本会话生效的权限档位与它允许做什么（投影已把 preset / 沙箱 / 审批三个旋钮折成一个值）',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 85
    },
    {
      id: 'jobs', name: 'Background Jobs', nameZh: '后台作业',
      desc: 'This session\'s background jobs: how many are running, the longest one, and what the newest is',
      descZh: '本会话的后台作业：几个在跑、最久跑了多久、最近一个是什么',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 86
    },
    {
      id: 'sys-disk', name: 'Disk & Self-check', nameZh: '磁盘与自检',
      desc: 'Free space per drive, the DSH session-log footprint and its growth, and the web process\'s own usage — the operational risks a long-running harness actually hits',
      descZh: '各盘剩余空间、DSH 会话日志的体积与增速、web 进程自身的占用——长跑 harness 最真实的运维风险',
      group: 'device', builtin: false, defaultInstalled: false, sizes: ['2x4'], order: 87
    },
    {
      id: 'window-forecast', name: 'Window Forecast', nameZh: '窗口预测',
      desc: 'At the current pace, will the 5h / weekly quota window hit its cap before it resets? (Quota Manager only covers the monthly window)',
      descZh: '按当前速率，5 小时 / 周额度窗口会不会在重置前打满（额度管理只管月窗口）',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 88
    },
    {
      id: 'sys-net', name: 'Network Throughput', nameZh: '网络吞吐',
      desc: 'Live per-adapter receive / transmit rate (a counter delta) for this machine, plus the busiest adapter',
      descZh: '本机网卡的实时收发速率（两次计数采样差分），以及当前最忙的那张网卡',
      group: 'device', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 89
    },
    {
      id: 'sys-power', name: 'Power', nameZh: '供电',
      desc: 'Whether this machine runs on battery, its charge and remaining runtime, and the active Windows power scheme',
      descZh: '是否在用电池、剩余电量与预计续航，以及当前 Windows 电源方案',
      group: 'device', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 90
    },
    {
      id: 'sys-procs', name: 'Top Processes', nameZh: '内存大户',
      desc: 'The top processes by working-set memory — who is eating the RAM while several agents or models run at once',
      descZh: '按工作集内存排序的前几名进程；多 agent / 多模型并行时回答「谁把内存吃满了」',
      group: 'device', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 91
    },
    {
      id: 'session-cost', name: 'Session Cost', nameZh: '会话成本',
      desc: 'Folds this session\'s four token buckets into money using the price table, and says which table it used (official / reseller / free route / estimated)',
      descZh: '把本会话的四桶 token 按价格表折成钱，并标出这个金额的来源（官方价 / 中转价 / 免费路由 / 估算价）',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 93
    },
    {
      id: 'github-notify', name: 'To Review', nameZh: '待我处理',
      desc: 'Unread GitHub threads waiting on you: review requests, mentions and assignments, plus the newest one — needs a token or a gh login (no card at all when signed out)',
      descZh: 'GitHub 上等我的未读线程：review 请求 / @提及 / 指派，以及最新的一条；需要 token 或 gh 登录（未登录时该卡不出现）',
      group: 'github', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 94
    }
  ].sort((a, b) => a.order - b.order)
};

window.DASH_WIDGETS.byId = Object.fromEntries(
  window.DASH_WIDGETS.widgets.map((w) => [w.id, w])
);
