/**
 * dsh-widgets showcase — widget data. GENERATED by website/gen-site.mjs.
 *
 * SOURCE OF TRUTH: this file mirrors the real project unit directories
 * `src/widgets/<id>/manifest.json` (33 units, v1.6.0). Every field
 * below comes from those manifests — nothing is invented. Regenerate with
 * `node website/gen-site.mjs`; verify with `--check` (wired into verify.mjs).
 */
window.DASH_WIDGETS = {
  version: '1.6.0',
  npm: 'dsh-widgets',
  repo: 'https://github.com/Physicolor/dsh-widgets',
  issues: 'https://github.com/Physicolor/dsh-widgets/issues',
  releases: 'https://github.com/Physicolor/dsh-widgets/releases',
  site: 'https://physicolor.github.io/dsh-widgets/',
  installCmd: 'dsh plugin --profile web add dsh-widgets',
  compat: 'DeepSeek Harness 0.1.0-rc.6+',
  groups: {
    'system': { en: 'System', zh: '系统' },
    'commandcode': { en: 'Command Code', zh: 'Command Code' },
    'coding-plan': { en: 'Coding Plan Usage', zh: 'Coding Plan 用量' },
    'opencode-go': { en: 'OpenCode Go', zh: 'OpenCode Go' },
    'pricing': { en: 'Peak Pricing', zh: '峰谷定价' },
    'device': { en: 'Device', zh: '设备状态' },
    'other': { en: 'Others', zh: '其它' }
  },
  widgets: [
    {
      id: 'counts', name: 'Turns · Steps', nameZh: '轮次·步数',
      desc: 'Turns and steps of the current session',
      descZh: '本轮会话的轮次与步骤计数',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 10
    },
    {
      id: 'llm', name: 'LLM Time', nameZh: 'LLM 时长',
      desc: 'Cumulative model inference time',
      descZh: '模型推理累计耗时',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 11
    },
    {
      id: 'tool', name: 'Tool Calls', nameZh: '工具调用',
      desc: 'Cumulative tool call time',
      descZh: '工具调用累计耗时',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 12
    },
    {
      id: 'ttft', name: 'Avg TTFT', nameZh: '首 token 平均',
      desc: 'Average first-token latency',
      descZh: '平均首 token 延迟',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 13
    },
    {
      id: 'tps', name: 'Rate', nameZh: '速率',
      desc: 'Decode throughput speed',
      descZh: '解码吞吐速度',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 14
    },
    {
      id: 'cache', name: 'Cache Hit', nameZh: '缓存命中',
      desc: 'Input cache hit ratio',
      descZh: '输入缓存的命中比例',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 15
    },
    {
      id: 'tokens', name: 'Tokens', nameZh: 'Tokens',
      desc: 'Input & output token counts',
      descZh: '输入与输出 token 计数',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 16
    },
    {
      id: 'context', name: 'Compact', nameZh: '一键压缩',
      desc: 'Context usage percent; top-right button compacts after two taps',
      descZh: '上下文占用百分比，右上按钮两次点击执行压缩',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 20
    },
    {
      id: 'context-water', name: 'Context Level', nameZh: '上下文水位',
      desc: 'System/tools/messages share as a segmented bar',
      descZh: '上下文系统/工具/消息占比分段条',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2', '2x4'], order: 21
    },
    {
      id: 'task', name: 'Tasks', nameZh: '任务',
      desc: 'Counts of in-progress / completed / pending tasks',
      descZh: '当前任务的进行中/已完成/待办计数',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 22
    },
    {
      id: 'quote', name: 'Daily Quote', nameZh: '今日寄语',
      desc: 'Shows a custom sentence you typed (hidden while empty)',
      descZh: '显示你自定义的一句话（未填写文本时不显示内容）',
      group: 'other', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 30
    },
    {
      id: 'heatmap', name: 'Token Heatmap', nameZh: '用量热度图',
      desc: 'Daily token usage heatmap (self-accounted). 2×2 shows a ~3-month calendar, 2×4 the ~half-year history; switch size in the market',
      descZh: '每日 Token 用量热度图（自记账）。2×2 显示近 3 个月日历，2×4 显示近半年全部用量点；大小可在市场左右切换',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2', '2x4'], order: 40
    },
    {
      id: 'heatmap-bars', name: 'Token Bars', nameZh: '用量柱状图',
      desc: 'Vertical bars of the last 7 days of token usage; same height as the calendar view',
      descZh: '最近 7 天 Token 用量的垂直柱状图，柱区高度与日历图一致',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 41
    },
    {
      id: 'quota-manage', name: 'Quota Manager', nameZh: '额度管理',
      desc: 'Projects the month-end usage percent from the billing period\'s pace, with today\'s tokens vs the recommended budget',
      descZh: '按账期趋势预测月末用量百分比，并给出今日 token 用量与今日推荐用量',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 42
    },
    {
      id: 'usage-bars', name: 'Usage Bars', nameZh: '用量对比',
      desc: 'OpenCode rolling/weekly/monthly usage bars',
      descZh: 'OpenCode 滚动/周/月三窗口用量柱状图',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 50
    },
    {
      id: 'usage-rings', name: 'Usage Rings', nameZh: '用量环图',
      desc: 'OpenCode rolling/weekly/monthly usage rings',
      descZh: 'OpenCode 滚动/周/月三窗口用量环形图',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 51
    },
    {
      id: 'usage-rolling', name: 'Rolling Usage', nameZh: '滚动用量',
      desc: 'OpenCode Go rolling-window usage quota',
      descZh: 'OpenCode Go 滚动窗口用量配额',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 52
    },
    {
      id: 'usage-weekly', name: 'Weekly Usage', nameZh: '每周用量',
      desc: 'OpenCode Go weekly usage quota',
      descZh: 'OpenCode Go 每周用量配额',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 53
    },
    {
      id: 'usage-monthly', name: 'Monthly Usage', nameZh: '每月用量',
      desc: 'OpenCode Go monthly usage quota',
      descZh: 'OpenCode Go 每月用量配额',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 54
    },
    {
      id: 'cc-whoami', name: 'Account', nameZh: '账户',
      desc: 'Current Command Code account identity (name / email / org)',
      descZh: '当前 Command Code 账户身份（用户名 / 邮箱 / 组织）',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 60
    },
    {
      id: 'peak-pricing', name: 'Peak Pricing', nameZh: '峰谷定价',
      desc: 'DeepSeek V4 peak pricing: whether now is a peak window (Beijing time, weekdays 09:00–12:00 & 14:00–18:00 are peak)',
      descZh: 'DeepSeek V4 峰谷定价：当前是否处于高峰时段（北京时间，工作日 09:00–12:00 与 14:00–18:00 为高峰）',
      group: 'pricing', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 60
    },
    {
      id: 'sys-cpu', name: 'CPU Status', nameZh: 'CPU 状态',
      desc: 'Local CPU utilization and memory usage',
      descZh: '本机 CPU 利用率与内存占用',
      group: 'system', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 60
    },
    {
      id: 'cc-usage', name: 'Usage', nameZh: '用量',
      desc: 'Requests, success rate, tokens and spend for the billing period',
      descZh: '账期内的请求数、成功率、Token 与消费摘要',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 61
    },
    {
      id: 'sys-gpu', name: 'GPU Status', nameZh: 'GPU 状态',
      desc: 'Local NVIDIA GPU VRAM, utilization and temperature',
      descZh: '本机 NVIDIA GPU 显存、利用率与温度',
      group: 'system', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 61
    },
    {
      id: 'cc-credits', name: 'Credits', nameZh: '额度',
      desc: 'Credit balance with 5h / weekly window usage',
      descZh: 'Credits 余额与 5h / 周额度窗口用量',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 62
    },
    {
      id: 'sys-rings', name: 'CPU · GPU Rings', nameZh: 'CPU·GPU 环图',
      desc: 'CPU / GPU utilization twin rings',
      descZh: 'CPU / GPU 利用率双环形图',
      group: 'system', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 62
    },
    {
      id: 'cc-windows', name: 'Windows', nameZh: '窗口',
      desc: '5h / weekly / monthly usage as rings',
      descZh: '5h / 周 / 月 三窗口用量环图',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 63
    },
    {
      id: 'sys-board', name: 'System Monitor', nameZh: '系统监控',
      desc: 'CPU / memory / GPU VRAM and utilization dashboard rings',
      descZh: 'CPU/内存/GPU 显存与利用率全指标环形看板',
      group: 'system', builtin: false, defaultInstalled: false, sizes: ['2x4'], order: 63
    },
    {
      id: 'cc-subscription', name: 'Plan', nameZh: '套餐',
      desc: 'Current plan, status and billing period end',
      descZh: '当前套餐、状态与账期结束时间',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 64
    },
    {
      id: 'sys-gpu-line', name: 'GPU Utilization', nameZh: 'GPU 利用率',
      desc: 'GPU utilization sparkline (last ~20 min)',
      descZh: 'GPU 利用率折线（最近约 20 分钟）',
      group: 'device', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 64
    },
    {
      id: 'cc-window-5h', name: '5h window', nameZh: '5h 窗口',
      desc: '5-hour quota window usage percent and reset time',
      descZh: '5 小时额度窗口用量百分比与重置时间',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 65
    },
    {
      id: 'cc-window-weekly', name: 'Weekly window', nameZh: '周窗口',
      desc: 'Weekly quota window usage percent and reset time',
      descZh: '周额度窗口用量百分比与重置时间',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 66
    },
    {
      id: 'cc-window-monthly', name: 'Monthly window', nameZh: '月窗口',
      desc: 'Billing-period usage percent ((allowance − remaining) / allowance) and period end',
      descZh: '账期月额度用量百分比（额度 − 剩余 / 额度）与账期结束时间',
      group: 'commandcode', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 67
    }
  ].sort((a, b) => a.order - b.order)
};

window.DASH_WIDGETS.byId = Object.fromEntries(
  window.DASH_WIDGETS.widgets.map((w) => [w.id, w])
);
