/**
 * dsh-widgets showcase — widget data.
 *
 * SOURCE OF TRUTH: this file is generated by hand from the real project unit
 * directories `src/widgets/<id>/manifest.json` (19 units, v1.4.0). Every field
 * below comes from those manifests — nothing is invented. If the registry
 * changes, regenerate this table from `manifest.json` files.
 */
window.DASH_WIDGETS = {
  version: '1.4.0',
  npm: 'dsh-widgets',
  repo: 'https://github.com/Physicolor/dsh-widgets',
  issues: 'https://github.com/Physicolor/dsh-widgets/issues',
  releases: 'https://github.com/Physicolor/dsh-widgets/releases',
  installCmd: 'dsh plugin --profile web add dsh-widgets',
  compat: 'DeepSeek Harness 0.1.0-rc.6+',
  groups: {
    system: { en: 'System', zh: '系统' },
    'coding-plan': { en: 'Coding Plan Usage', zh: 'Coding Plan 用量' },
    'opencode-go': { en: 'OpenCode Go', zh: 'OpenCode Go' },
    pricing: { en: 'Peak Pricing', zh: '峰谷定价' },
    other: { en: 'Others', zh: '其它' }
  },
  widgets: [
    {
      id: 'counts', name: 'Turns · Steps', nameZh: '轮次·步数',
      desc: 'Turns and steps of the current session',
      descZh: '本轮会话的轮次与步骤计数',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 10
    },
    {
      id: 'llm', name: 'LLM Time', nameZh: 'LLM 时长',
      desc: 'Cumulative model inference time',
      descZh: '模型推理累计耗时',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 11
    },
    {
      id: 'tool', name: 'Tool Calls', nameZh: '工具调用',
      desc: 'Cumulative tool call time',
      descZh: '工具调用累计耗时',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 12
    },
    {
      id: 'ttft', name: 'Avg TTFT', nameZh: '首 token 平均',
      desc: 'Average first-token latency',
      descZh: '平均首 token 延迟',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 13
    },
    {
      id: 'tps', name: 'Rate', nameZh: '速率',
      desc: 'Decode throughput speed',
      descZh: '解码吞吐速度',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 14
    },
    {
      id: 'cache', name: 'Cache Hit', nameZh: '缓存命中',
      desc: 'Input cache hit ratio',
      descZh: '输入缓存的命中比例',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 15
    },
    {
      id: 'tokens', name: 'Tokens', nameZh: 'Tokens',
      desc: 'Input & output token counts',
      descZh: '输入与输出 token 计数',
      group: 'system', builtin: true, defaultInstalled: true, sizes: ['2x2'], order: 16
    },
    {
      id: 'context', name: 'Compact', nameZh: '一键压缩',
      desc: 'Context usage percent; top-right button compacts after two taps',
      descZh: '上下文占用百分比，右上按钮两次点击执行压缩',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 20
    },
    {
      id: 'context-water', name: 'Context Level', nameZh: '上下文水位',
      desc: 'System/tools/messages share as a segmented bar',
      descZh: '上下文系统/工具/消息占比分段条',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2', '2x4'], order: 21
    },
    {
      id: 'task', name: 'Tasks', nameZh: '任务',
      desc: 'Counts of in-progress / completed / pending tasks',
      descZh: '当前任务的进行中/已完成/待办计数',
      group: 'system', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 22
    },
    {
      id: 'quote', name: 'Daily Quote', nameZh: '今日寄语',
      desc: 'Shows a custom sentence you typed (hidden while empty)',
      descZh: '显示你自定义的一句话（未填写文本时不显示内容）',
      group: 'other', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 30
    },
    {
      id: 'heatmap', name: 'Token Heatmap', nameZh: '用量热度图',
      desc: 'Daily token usage heatmap (self-accounted). 2×2 shows a ~3-month calendar, 2×4 the ~half-year history',
      descZh: '每日 Token 用量热度图（自记账）。2×2 显示近 3 个月日历，2×4 显示近半年全部用量点',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2', '2x4'], order: 40
    },
    {
      id: 'heatmap-bars', name: 'Token Bars', nameZh: '用量柱状图',
      desc: 'Vertical bars of the last 7 days of token usage; same height as the calendar view',
      descZh: '最近 7 天 Token 用量的垂直柱状图，柱区高度与日历图一致',
      group: 'coding-plan', builtin: true, defaultInstalled: false, sizes: ['2x2'], order: 41
    },
    {
      id: 'usage-bars', name: 'Usage Bars', nameZh: '用量对比',
      desc: 'OpenCode rolling/weekly/monthly usage bars',
      descZh: 'OpenCode 滚动/周/月三窗口用量柱状图',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 50
    },
    {
      id: 'usage-rings', name: 'Usage Rings', nameZh: '用量环图',
      desc: 'OpenCode rolling/weekly/monthly usage rings',
      descZh: 'OpenCode 滚动/周/月三窗口用量环形图',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 51
    },
    {
      id: 'usage-rolling', name: 'Rolling Usage', nameZh: '滚动用量',
      desc: 'OpenCode Go rolling-window usage quota',
      descZh: 'OpenCode Go 滚动窗口用量配额',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 52
    },
    {
      id: 'usage-weekly', name: 'Weekly Usage', nameZh: '每周用量',
      desc: 'OpenCode Go weekly usage quota',
      descZh: 'OpenCode Go 每周用量配额',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 53
    },
    {
      id: 'usage-monthly', name: 'Monthly Usage', nameZh: '每月用量',
      desc: 'OpenCode Go monthly usage quota',
      descZh: 'OpenCode Go 每月用量配额',
      group: 'opencode-go', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 54
    },
    {
      id: 'peak-pricing', name: 'Peak Pricing', nameZh: '峰谷定价',
      desc: 'DeepSeek V4 peak pricing: whether now is a peak window (Beijing time, weekdays 09:00–12:00 & 14:00–18:00 are peak)',
      descZh: 'DeepSeek V4 峰谷定价：当前是否处于高峰时段（北京时间，工作日 09:00–12:00 与 14:00–18:00 为高峰）',
      group: 'pricing', builtin: false, defaultInstalled: false, sizes: ['2x2'], order: 60
    }
  ].sort((a, b) => a.order - b.order)
};

window.DASH_WIDGETS.byId = Object.fromEntries(
  window.DASH_WIDGETS.widgets.map((w) => [w.id, w])
);