#!/usr/bin/env node
/**
 * The tree printer for docs/architecture/CODE_MAP.md.
 *
 * The source of truth is `git ls-files`, so the output is exactly what the REPOSITORY
 * contains: no node_modules, no gitignored scratch (docs/poster, docs/backup, local
 * probes, lib/types). Each entry gets a one-line purpose from the table below.
 *
 * Regenerate with: node scripts/print-tree.mjs
 */
import { execFileSync } from 'node:child_process'

const files = execFileSync('git', ['ls-files'], { encoding: 'utf8' }).split('\n').filter(Boolean)
const COLLAPSE_UNITS = process.argv.includes('--collapse-units')

/** One-line purpose per PATH (file or directory). Unlisted paths print bare. */
const NOTES = {
  '.github/workflows/publish.yml': 'npm Trusted Publishing (OIDC) on a v* tag',
  '.github/workflows/pages.yml': 'deploys website/ to GitHub Pages',
  'src/index.ts': 'host entry: compose only (inject + loop over HOST_ROUTES)',
  'src/host': 'host half: one module per upstream channel',
  'src/host/context.ts': 'the ctx contract (webServer / credentials / get / effect)',
  'src/host/http.ts': 'memoTtl, readJsonBody, route-cache policy',
  'src/host/exec.ts': 'the one promisified execFile two channels share',
  'src/host/routes.ts': 'the route registry: add a channel = add a module + one line',
  'src/host/opencode.ts': '/api/opencode-usage + /api/opencode-usage-multi',
  'src/host/commandcode.ts': '/api/commandcode-usage: 4 endpoints x pool keys + memo',
  'src/host/usage-daily.ts': '/api/widgets-usage-daily: the usage-center adapter',
  'src/host/github.ts': '/api/github: credential ladder + five slice caches',
  'src/host/state-file.ts': '/api/widgets-state: atomic tmp+rename write',
  'src/host/sysinfo.ts': '/api/sysinfo: CPU delta / memory / nvidia-smi + ring buffer',
  'src/widgets': 'the 40 widget UNITS — one folder per widget',
  'src/widgets/_shared': 'dictionary keys several units share',
  'src/widgets-template': 'copy-me unit + the authoring README',
  'src/client': 'browser half',
  'src/client/index.ts': 'client entry: bridge + slot wiring + header/settings surfaces',
  'src/client/slots-service.d.ts': 'types the runtime `slots` service (upstream does not)',
  'src/client/i18n.ts': 'shell dictionary + locale-service adapter',
  'src/client/generated.registry.ts': 'GENERATED by scripts/gen-registry.mjs — never hand-edit',
  'src/client/css-modules.d.ts': 'ambient `*.module.css` declaration',
  'src/client/runtime': 'framework plumbing that is not React',
  'src/client/runtime/bridge.ts': 'the snapshot type every surface reads',
  'src/client/runtime/prefs.ts': 'prefs shape + normalize + localStorage load/save',
  'src/client/runtime/host-sync.ts': 'the /api/widgets-state client (debounced PUT)',
  'src/client/runtime/controller.ts': 'the controller interface the settings pages take',
  'src/client/data': 'turning external input into the bridge',
  'src/client/data/collector.tsx': 'the dock component that polls/routes every source',
  'src/client/data/session-stats.ts': 'the live conversation projection -> Stats',
  'src/client/families': 'per-source payload parsing + card renderers',
  'src/client/render': 'how a card becomes pixels',
  'src/client/render/CardBody.tsx': 'the card shell: title, body, chart dispatch, skeleton',
  'src/client/render/card-geometry.ts': 'corner radius / inner padding maths',
  'src/client/render/icons.tsx': 'the svg glyphs the surfaces use',
  'src/client/render/charts': 'one file per chart kind + the registry',
  'src/client/render/charts/registry.ts': 'kind -> renderer: add a chart = add a file + one line',
  'src/client/render/preview': 'the settings previews reuse these (no live data)',
  'src/client/rail': 'the right-hand rail',
  'src/client/rail/geometry.ts': 'rail space/budget maths (pure reads + solving)',
  'src/client/rail/measure.ts': 'observers, anchor probes, width tracking, yield beat',
  'src/client/rail/rail-view.tsx': 'the rail slot body: deck grid, wave, add panel, drawer',
  'src/client/rail/wave/RailWave.tsx': 'the magnification wave component (rAF loops, hit tests)',
  'src/client/rail/wave/wave-geometry.ts': 'wave layout: rows, scales, nearest slot, reflow',
  'src/client/surfaces': 'settings + market pages',
  'src/client/surfaces/Settings.tsx': 'the tabbed components page (list + detail)',
  'src/client/surfaces/config/ConfigTab.tsx': 'component config: order list + fields + preview',
  'src/client/surfaces/market/MarketTab.tsx': 'component market: gallery, stage, ghost, install',
  'src/client/surfaces/settings-nav-glyph.ts': 'the settings nav icon shim (official hardcodes)',
  'src/client/surfaces/layout.ts': 'the three layout constants the pages share',
  'src/client/styles': 'tokens + five layers; the import order in client/index.ts is the cascade',
  'src/client/styles/tokens.module.css': 'the :root vocabulary the other sheets read',
  'src/client/lib': 'framework-agnostic helpers',
  'src/client/lib/contract': 'the widget contract',
  'src/client/lib/contract/types.ts': 'every shape a unit/renderer/shell exchanges (zero imports)',
  'src/client/lib/contract/helpers.ts': 'defineWidget, label resolvers, instance keys, sizesOf',
  'src/client/lib/format.ts': 'number / duration / percent formatting',
  'src/client/lib/heatmap-accounting.ts': 'the fallback daily-token log (no usage-center)',
  'src/client/lib/quota-math.ts': 'credit -> token-rate maths',
  'src/client/lib/morph-spring.ts': 'the spring curve the wave animates with',
  'scripts': 'offline gates, build helpers, local probes',
  'scripts/gen-registry.mjs': 'G1: scans src/widgets/ and emits generated.registry.ts',
  'scripts/validate-widget-unit.mjs': 'G2: per-unit contract + locale completeness',
  'scripts/verify-tsc-baseline.mjs': 'G3: typecheck (baseline is empty = zero errors required)',
  'scripts/snapshot-render.mjs': 'G4: 110 render outputs vs the recorded baseline',
  'scripts/snapshot/render-harness.ts': 'G4 harness: calls every render offline',
  'scripts/extract-css.mjs': 'G5: compiled-CSS concatenation vs the baseline',
  'scripts/audit-move-only.mjs': 'G6: added vs removed lines for a pure-move commit',
  'scripts/snapshot-host-routes.mjs': 'G7: 14 host route cases with stubs, no live server',
  'scripts/build-types.mjs': 'emits lib/types + the css-modules shim the entries reference',
  'scripts/verify-published-types.mjs': 'G8: a throwaway consumer resolves both entry types',
  'scripts/lib/chrome.cjs': 'resolves the newest installed playwright chromium',
  'scripts/print-tree.mjs': 'prints this tree',
  'docs/architecture': 'the audit, the plan, the report, and the recorded baselines',
  'docs/architecture/CODE_MAP.md': 'THIS FILE — where everything is implemented',
  'docs/architecture/CURRENT_ARCHITECTURE.md': 'Phase 0 audit (pre-refactor snapshot)',
  'docs/architecture/REFACTOR_PLAN.md': 'the plan, with execution status inline',
  'docs/architecture/ARCHITECTURE_REFACTOR_REPORT.md': 'the report (round 1 = s1-15, round 2 = s16)',
  'docs/architecture/baseline': 'the recorded gate baselines',
  'docs/verify-sysinfo.mjs': 'offline host sysinfo contract (also runs in CI)',
  'docs/verify-skeleton-shapes.cjs': 'live: skeleton silhouettes, 19 cards',
  'docs/verify-nav-glyph.cjs': 'live: the settings nav icon shim',
  'docs/verify-report3': 'the 2026-09-17 rail/nav incident record + its probes',
  'lib': 'BUILT artifacts (the plugin loader reads these straight from this checkout)',
  'website': 'the plugin site (generated pages + verify.mjs)',
}

// ---- assemble the tree ----
const tree = new Map()
for (const f of files) {
  const parts = f.split('/')
  let path = ''
  for (let i = 0; i < parts.length; i++) {
    path = path === '' ? parts[i] : `${path}/${parts[i]}`
    const isFile = i === parts.length - 1
    if (!tree.has(path)) tree.set(path, { isFile, children: [] })
    if (!isFile) {
      const parent = i === 0 ? null : parts.slice(0, i).join('/')
      const node = tree.get(path)
      if (parent !== null && !tree.get(parent).children.includes(path)) tree.get(parent).children.push(path)
    } else {
      const parent = i === 0 ? null : parts.slice(0, i).join('/')
      if (parent !== null && !tree.get(parent).children.includes(path)) tree.get(parent).children.push(path)
    }
  }
}

const out = []
const sortChildren = (p) => {
  const node = tree.get(p)
  node.children.sort((a, b) => {
    const ad = !tree.get(a).isFile
    const bd = !tree.get(b).isFile
    if (ad !== bd) return ad ? -1 : 1
    return a.localeCompare(b)
  })
  for (const c of node.children) if (!tree.get(c).isFile) sortChildren(c)
}
const roots = [...tree.keys()].filter((p) => !p.includes('/'))
roots.sort((a, b) => {
  const ad = !tree.get(a).isFile
  const bd = !tree.get(b).isFile
  if (ad !== bd) return ad ? -1 : 1
  return a.localeCompare(b)
})
for (const r of roots) if (!tree.get(r).isFile) sortChildren(r)

function emit(p, prefix, isLast) {
  const node = tree.get(p)
  const name = p.split('/').pop() + (node.isFile ? '' : '/')
  const note = NOTES[p]
  // --collapse-units: one line per widget unit instead of 2-3 lines each. 40 units
  // is 40 folders by design; the per-unit files are always the same shape.
  if (COLLAPSE_UNITS && /^src\/widgets\/[^/]+$/.test(p) && !node.isFile && !p.endsWith('_shared')) {
    const inner = node.children.map((c) => tree.get(c).isFile ? c.split('/').pop() : `${c.split('/').pop()}/`)
    out.push(`${prefix}${isLast ? '`-- ' : '|-- '}${name}    # ${inner.join(' + ')}`)
    return
  }
  out.push(`${prefix}${isLast ? '`-- ' : '|-- '}${name}${note === undefined ? '' : `    # ${note}`}`)
  const nextPrefix = `${prefix}${isLast ? '    ' : '|   '}`
  node.children.forEach((c, i) => emit(c, nextPrefix, i === node.children.length - 1))
}
out.push('.')
roots.forEach((r, i) => emit(r, '', i === roots.length - 1))

/**
 * `--inject <markdown>`: rewrite the block between the TREE_START/TREE_END markers of
 * that file instead of printing. Keeps docs/architecture/CODE_MAP.md's tree in sync
 * with the repository by construction.
 */
const injectAt = process.argv.indexOf('--inject')
if (injectAt > 0 && process.argv[injectAt + 1] !== undefined) {
  const { readFileSync, writeFileSync } = await import('node:fs')
  const target = process.argv[injectAt + 1]
  const text = readFileSync(target, 'utf8')
  const marker = /<!-- TREE_START -->[\s\S]*?<!-- TREE_END -->/
  if (!marker.test(text)) { console.error(`[print-tree] no TREE_START/TREE_END markers in ${target}`); process.exit(1) }
  const block = `<!-- TREE_START -->\n\`\`\`text\n${out.join('\n')}\n\`\`\`\n<!-- TREE_END -->`
  writeFileSync(target, text.replace(marker, block), 'utf8')
  console.error(`[print-tree] injected ${out.length - 1} tree entries into ${target}`)
} else {
  console.log(out.join('\n'))
  console.error(`[print-tree] ${files.length} tracked file(s), ${out.length - 1} tree entries`)
}
