#!/usr/bin/env node
/**
 * dsh-widgets website — static site generator.
 *
 * The showcase must be readable WITHOUT JavaScript: crawlers, no-JS readers and
 * link previews all need the real widget list in the HTML source. This script
 * derives every widget fact from the REAL source of truth and writes it into
 * the page:
 *
 *   source of truth   src/widgets/<id>/manifest.json  (+ js/previews.js for the
 *                     primary pattern / interaction, read from the REAL render
 *                     output rather than re-declared)
 *   writes            website/js/data.js          — the widget table
 *                     website/index.html          — gallery markup + ItemList
 *
 * Usage:
 *   node website/gen-site.mjs           # regenerate
 *   node website/gen-site.mjs --check   # fail if either artifact is stale
 *
 * It never touches a version number: the package version is READ from
 * package.json and only ever copied into the page.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(SITE, '..');
const WIDGETS_DIR = join(ROOT, 'src', 'widgets');
const DATA_OUT = join(SITE, 'js', 'data.js');
const HTML_OUT = join(SITE, 'index.html');

const CHECK = process.argv.includes('--check');
const VERSION = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;

const GROUPS = {
  system: { en: 'System', zh: '系统' },
  commandcode: { en: 'Command Code', zh: 'Command Code' },
  'coding-plan': { en: 'Coding Plan Usage', zh: 'Coding Plan 用量' },
  'opencode-go': { en: 'OpenCode Go', zh: 'OpenCode Go' },
  pricing: { en: 'Peak Pricing', zh: '峰谷定价' },
  device: { en: 'Device', zh: '设备状态' },
  other: { en: 'Others', zh: '其它' }
};

/**
 * Site copy corrections. The product reads its market description from the
 * manifest, and one manifest string still describes a formula that was
 * superseded (see src/client/lib/cc-view.ts:157-188 and the audit's copyTruth
 * rule). The website shows the correct formula; the product manifest is owned
 * by the plugin and is left untouched.
 */
const DESC_FIXES = {
  'cc-window-monthly': {
    zh: '账期月额度用量百分比（额度 − 剩余 / 额度）与账期结束时间',
    en: 'Billing-period usage percent ((allowance − remaining) / allowance) and period end'
  }
};

/* ── read the manifests ─────────────────────────────────────── */
const widgets = [];
for (const id of readdirSync(WIDGETS_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory() && !d.name.startsWith('_'))
  .map((d) => d.name)) {
  const mf = join(WIDGETS_DIR, id, 'manifest.json');
  if (!existsSync(mf)) continue;
  const m = JSON.parse(readFileSync(mf, 'utf8'));
  const loc = (l, k) => m.locale?.[l]?.[`widget.${id}.${k}`] ?? '';
  const fix = DESC_FIXES[id];
  widgets.push({
    id,
    name: loc('en', 'name') || id,
    nameZh: loc('zh', 'name') || id,
    desc: fix ? fix.en : (loc('en', 'desc') || ''),
    descZh: fix ? fix.zh : (loc('zh', 'desc') || ''),
    group: m.group ?? 'other',
    builtin: m.builtin !== false,
    defaultInstalled: m.defaultInstalled === true,
    sizes: Array.isArray(m.sizes) && m.sizes.length ? m.sizes : ['2x2'],
    order: typeof m.order === 'number' ? m.order : 1000
  });
}
widgets.sort((a, b) => a.order - b.order || (a.id < b.id ? -1 : 1));

/* ── the REAL render output tells us the pattern + interaction ─
 * previews.js / i18n.js / grammar.js are plain browser scripts (no DOM at load
 * time), so they can be evaluated here against a stub window — which means the
 * generated data is derived from the SAME code the page runs, not a copy. */
const win = {};
function load(file, global) {
  const src = readFileSync(join(SITE, 'js', file), 'utf8');
  return new Function('window', `${src}\nreturn window.${global};`)(win);
}
load('i18n.js', 'DASH_I18N');
const GRAMMAR = load('grammar.js', 'DASH_GRAMMAR');
const PREVIEWS = load('previews.js', 'DASH_PREVIEWS');

for (const w of widgets) {
  const out = PREVIEWS.out(w, { unit: 150, size: w.sizes[0] });
  w.patternKey = GRAMMAR.patternOf(out);
  w.interactionKey = GRAMMAR.interactionOf(out);
}

/* ── js/data.js ─────────────────────────────────────────────── */
const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const dataBody = widgets.map((w) => `    {
      id: ${q(w.id)}, name: ${q(w.name)}, nameZh: ${q(w.nameZh)},
      desc: ${q(w.desc)},
      descZh: ${q(w.descZh)},
      group: ${q(w.group)}, builtin: ${w.builtin}, defaultInstalled: ${w.defaultInstalled}, sizes: [${w.sizes.map(q).join(', ')}], order: ${w.order}
    }`).join(',\n');

const dataText = `/**
 * dsh-widgets showcase — widget data. GENERATED by website/gen-site.mjs.
 *
 * SOURCE OF TRUTH: this file mirrors the real project unit directories
 * \`src/widgets/<id>/manifest.json\` (${widgets.length} units, v${VERSION}). Every field
 * below comes from those manifests — nothing is invented. Regenerate with
 * \`node website/gen-site.mjs\`; verify with \`--check\` (wired into verify.mjs).
 */
window.DASH_WIDGETS = {
  version: ${q(VERSION)},
  npm: 'dsh-widgets',
  repo: 'https://github.com/Physicolor/dsh-widgets',
  issues: 'https://github.com/Physicolor/dsh-widgets/issues',
  releases: 'https://github.com/Physicolor/dsh-widgets/releases',
  site: 'https://physicolor.github.io/dsh-widgets/',
  installCmd: 'dsh plugin --profile web add dsh-widgets',
  compat: 'DeepSeek Harness 0.1.0-rc.6+',
  groups: {
${Object.entries(GROUPS).map(([k, v]) => `    ${q(k)}: { en: ${q(v.en)}, zh: ${q(v.zh)} }`).join(',\n')}
  },
  widgets: [
${dataBody}
  ].sort((a, b) => a.order - b.order)
};

window.DASH_WIDGETS.byId = Object.fromEntries(
  window.DASH_WIDGETS.widgets.map((w) => [w.id, w])
);
`;

/* ── gallery markup ─────────────────────────────────────────── */
function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function cardHtml(w) {
  const g = GROUPS[w.group] || { zh: w.group, en: w.group };
  const sizes = w.sizes.map((s) => s.replace('x', '×')).join(' ');
  return `          <article class="widget-card" data-group="${esc(w.group)}" data-widget="${esc(w.id)}" role="listitem">
            <div class="widget-preview"><div class="wg-slot widget-stage-lg" data-preview="${esc(w.id)}" data-size="2x2"></div></div>
            <div class="widget-body">
              <div class="widget-name-row">
                <span class="widget-name">${esc(w.nameZh)}<span class="widget-name-en">${esc(w.name)}</span></span>
                <span class="widget-id">${esc(w.id)}</span>
              </div>
              <p class="widget-desc">${esc(w.descZh)}<span class="widget-desc-en"> ${esc(w.desc)}</span></p>
              <div class="widget-meta">
                <span class="badge" data-i18n="group.${esc(w.group)}">${esc(g.zh)}</span>
                <span class="badge badge-size">${esc(sizes)}</span>
                <span class="badge badge-pattern" data-i18n="${esc(w.patternKey)}"></span>
                <span class="badge" data-i18n="${esc(w.interactionKey)}"></span>
                ${w.builtin
                  ? '<span class="badge badge-blue" data-i18n="badgeBuiltin">内置</span>'
                  : '<span class="badge badge-warn" data-i18n="badgeMarket">市场</span>'}
                ${w.defaultInstalled ? '<span class="badge badge-ok" data-i18n="badgePre">预装</span>' : ''}
                <button type="button" class="widget-open" data-widget="${esc(w.id)}" data-i18n="openDetail">解剖 / 审计</button>
              </div>
            </div>
          </article>`;
}

const galleryHtml = widgets.map(cardHtml).join('\n');

/* ── JSON-LD ItemList entries ───────────────────────────────── */
const jsonldItems = widgets.map((w, i) => `            {
              "@type": "ListItem",
              "position": ${i + 1},
              "name": ${JSON.stringify(`${w.nameZh} / ${w.name}`)},
              "description": ${JSON.stringify(`${w.descZh} ${w.desc}`)},
              "url": ${JSON.stringify(`https://github.com/Physicolor/dsh-widgets/tree/main/src/widgets/${w.id}`)}
            }`).join(',\n');

const jsonldBlock = `  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "ItemList",
    "@id": "https://physicolor.github.io/dsh-widgets/#widgets",
    "name": "dsh-widgets widget library",
    "description": "Every widget unit shipped by dsh-widgets, generated from the src/widgets unit manifests.",
    "numberOfItems": ${widgets.length},
    "itemListOrder": "https://schema.org/ItemListOrderAscending",
    "itemListElement": [
${jsonldItems}
    ]
  }
  </script>`;

/* ── inject into index.html ─────────────────────────────────── */
// line-ending agnostic: git may check the file out as CRLF on Windows
const read = (p) => readFileSync(p, 'utf8').replace(/\r\n/g, '\n');
const html = read(HTML_OUT);

function inject(source, name, body) {
  const re = new RegExp(`(<!-- gen:${name}:start -->)[\\s\\S]*?(<!-- gen:${name}:end -->)`);
  if (!re.test(source)) throw new Error(`marker gen:${name} not found in index.html`);
  return source.replace(re, `$1\n${body}\n          $2`);
}

let next = inject(html, 'gallery', galleryHtml);
next = inject(next, 'jsonld', jsonldBlock);

const summary = `${widgets.length} widgets · v${VERSION} · patterns ${[...new Set(widgets.map((w) => w.patternKey))].length}`;

if (CHECK) {
  const drift = [];
  if (read(DATA_OUT) !== dataText) drift.push('website/js/data.js');
  if (html !== next) drift.push('website/index.html');
  if (drift.length) {
    console.error(`STALE: ${drift.join(', ')} — run: node website/gen-site.mjs`);
    process.exit(1);
  }
  console.log(`gen-site --check: up to date (${summary})`);
} else {
  writeFileSync(DATA_OUT, dataText, 'utf8');
  writeFileSync(HTML_OUT, next, 'utf8');
  console.log(`wrote website/js/data.js + website/index.html (${summary})`);
}
